config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/category', to: 'pages#category', as: :category
  resources :vehicles do
    resources :bookings
  end
  resources :users, only: [:show, :index]
  resources :user do
    resources :bookings
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :vehicles, dependent: :nullify
  has_many :bookings
  mount_uploader :photo, PhotoUploader
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  mount_uploader :photo, PhotoUploader
  validates :photo, :description, :city, :price_day, :category, :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user: current_user)
    @bookings_as_owner = Booking.where(vehicle: current_user.vehicles)
  end

  # def show
  #   @booking = Booking.find(params[:id])
  # end

  def update
  if params[:param1] == "accepted"
    @booking = Booking.find(params[:id])
    @booking.status = "confirmed"
    @booking.save
    redirect_to user_bookings_path(current_user)
  else
    @booking = Booking.find(params[:id])
    @booking.status = "declined"
    @booking.save
    redirect_to user_bookings_path(current_user)
  end
  end

  def create
    @booking = Booking.new(booking_params)
    @vehicle = Vehicle.find(params[:vehicle_id])
    @booking.vehicle = @vehicle
    @booking.user = current_user
    if @booking.save
      redirect_to user_bookings_path(current_user)
    else
      redirect_to vehicle_path(@vehicle)
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to vehicle_bookings_path(@booking.vehicle)
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
  @user = current_user
end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  def index
    @vehicles = Vehicle.where(category: params[:category])
    @vehicles = @vehicles.where('city ILIKE ?', params[:city]) if params[:city].present?
    @vehicles = @vehicles.where('price_day <= ?', params[:price_day]) if params[:price_day].present?

  end

  def show
    @vehicle = Vehicle.find(params[:id])
    @booking = Booking.new
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user = current_user
    if @vehicle.save
      redirect_to user_path(@vehicle.user)
    else
      render 'new'
    end
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:photo, :description, :city, :price_day, :category, :title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1494363458195-0ce73b1afede?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
    <div class="container">
      <div class="container-fluid container-booking">
      <h1 id="title-booking">My Bookings</h1>

      <div class="tabs">
        <div>
          <p class="tab" id="renter-tab">As Renter</p>
        </div>
        <div>
          <p class="tab" id="owner-tab" >As Owner</p>
        </div>

      </div>

      <ul class="bookings_list" id="as_renter">
        <% @bookings.each do |booking| %>
        <li class="booking">
          <% if booking.vehicle.user.photo&.url %>
          <%= cl_image_tag booking.vehicle.user.photo.url(:bright_face), class: "avatar avatar-bordered" %>
          <% else %>
          <%= image_tag 'nopictavatar.svg', class: "avatar avatar-bordered" %>
          <% end %>
          <div class="booking-name">
            <h3> <%= booking.vehicle.user.name %> </h3>
            <p><%= booking.vehicle.city %></p>
            <p><%= booking.start_date %> to <%= booking.end_date %></p>
          </div>
          <div class="booking-body">
            <p><%= booking.vehicle.title %></p>
          </div>
          <div>
            <%= cl_image_tag booking.vehicle.photo.url, crop: :fill, class: "vehicle_small" %>
          </div>
          <div class="booking-status">
            <% if booking.status == "confirmed" %>
            <p class="status accepted"> Status: <%= booking.status %> </p>
            <% elsif booking.status == "declined" %>
            <p class="status declined"> Status: <%= booking.status %> </p>
            <% else %>
            <p class="status pending"> Status: <%= booking.status %> </p>
            <% end %>
            <p id="color-black"><%= booking.vehicle.price_day %> $/day</p>
          </div>
          <div class="booking-action">
            <%= link_to "Delete", user_booking_path(booking.user, booking), method: :delete %>
          </div>
        </li>
        <% end %>
      </ul>

      <ul class="bookings_list" id="as_owner">
        <% @bookings_as_owner.each do |booking| %>
        <li class="booking">
          <% if booking.user.photo&.url %>
          <%= cl_image_tag booking.user.photo.url(:bright_face), class: "avatar avatar-bordered" %>
          <% else %>
          <%= image_tag 'nopictavatar.svg', class: "avatar avatar-bordered" %>
          <% end %>
          <div class="booking-name">
            <h3> <%= booking.user.name %> </h3>
            <p><%= booking.vehicle.city %></p>
            <p><%= booking.start_date %> to <%= booking.end_date %></p>
          </div>
          <div class="booking-body">
            <p><%= booking.vehicle.title %></p>
          </div>
          <div>
            <%= cl_image_tag booking.vehicle.photo.url, crop: :fill, class: "vehicle_small" %>
          </div>
          <div class="booking-status">
            <% if booking.status == "confirmed" %>
            <p class="status accepted"> Status: <%= booking.status %> </p>
            <% elsif booking.status == "declined" %>
            <p class="status declined"> Status: <%= booking.status %> </p>
            <% else %>
            <p class="status pending"> Status: <%= booking.status %> </p>
            <% end %>
            <p id="color-black"><%= booking.vehicle.price_day %> $/day </p>
          </div>
          <div class="booking-action">
            <% if booking.status == "pending" %>
            <%= link_to "Confirm", vehicle_booking_path(booking.vehicle.id, booking.id, :param1 => 'accepted'), method: :patch %>
            <br>
            <%= link_to "Decline", vehicle_booking_path(booking.vehicle.id, booking.id), method: :patch %>
          </div>
            <% end %>
        </li>
        <% end %>
      </ul>
      </div>

    </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700" rel="stylesheet">
  <title>Vehicool</title>
  <%= favicon_link_tag asset_path('flavicon.png') %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <div class="content">
    <%= render 'shared/navbar' %>
    <%= yield %>
      <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  </div>

</body>
</html>

app/views/pages/category.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://images.unsplash.com/photo-1544716668-3d9044c0f2e4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80">
  <div class="container">
    <!--     <h1>Choose your Vehicool?</h1> -->
<!--     <div class="row">
      <div class="col-sm-12 col-lg-6"> -->
        <div class="cards">
          <%= link_to vehicles_path(category: "bicycle") do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1455719103652-8c015f564e2b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1189&q=80)">
            Bicycle
          </div>
          <% end  %>
          <%= link_to vehicles_path(category: "scooter") do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1521118629757-37b3f125272d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80)">
            Scooter
          </div>
          <% end %>
          <%= link_to vehicles_path(category: "car") do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1481628006330-476f1e161a05?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)">
            Car
          </div>
          <% end %>
          <%= link_to vehicles_path(category: "van") do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1008&q=80)">
            Van
          </div>
          <% end %>
<!--         </div>
      </div> -->
    </div>
  </div>
</div>

app/views/pages/home.html.erb
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1547010427-45f4b5a8092f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=839&q=80);">
    <div class="container">
      <h1>Rent a <strong>Vehicool</strong>!</h1>
      <p>Take it easy</p>
     <%= render 'shared/flashes' %>

     <%= link_to "Signin", new_user_session_path, class:"btn btn-success" unless user_signed_in?  %>
     <%= link_to "Signup", new_user_registration_path, class:"btn btn-primary" unless user_signed_in? %>
    <%= link_to "Book a new Vehicool", category_path, class:"btn btn-danger" if user_signed_in?  %>
    </div>
  </div>

app/views/shared/_card.html.erb
<%= link_to vehicle_path(vehicle) do %>

  <div class="card-trip">
  <%= cl_image_tag vehicle.photo.url, width: 800 ,crop: :fill %>
  <div class="card-trip-infos">
    <div>
      <h2><%= vehicle.title %></h2>
      <p><%= vehicle.city %></p>
    </div>
    <h2 class="card-trip-pricing">$ <%= vehicle.price_day %></h2>
    <%= cl_image_tag vehicle.user.photo.url(:bright_face), class:"card-trip-user avatar-bordered"%>
  </div>
</div>
<% end %>

app/views/shared/_flashes.html.erb
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<div class="footer footer-styling">
  <div class="footer-links">
    <a href="https://github.com/bhatter/vehico" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/lewagonberlin" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/lewagon" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://www.twitter.com/lewagonlondon" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/school/le-wagon/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.svg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Add my Vehicool", new_vehicle_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Book a new Vehicool", category_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if user_signed_in? %>
        <% if user_signed_in? && current_user.photo&.url %>
        <%= cl_image_tag current_user.photo.url(:bright_face), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
        <%= image_tag 'nopictavatar.svg', class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to user_path(current_user) do %>
            <i class="fa fa-user"></i> &nbsp <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to user_bookings_path(current_user) do %>
            <i class="fas fa-car"></i> &nbsp <%= t(".settings", default: "My Bookings") %>

            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i> &nbsp <%= t(".sign_out", default: "Logout") %>
            <% end %>
          </li>
        </ul>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Add my Vehicool", new_vehicle_path %></li>
        <li><%= link_to "Book a new Vehicool",  category_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>My Vehicles</h1>
</div>
<div class="container1">
  <div class="cards vehicle-cards">
    <% current_user.vehicles.each do |vehicle| %>
    <%= render './shared/card', vehicle: vehicle %>
    <% end %>
    </div>
</div>

app/views/vehicles/index.html.erb
<div class="container">
  <h1>All <%= params[:category].capitalize %>s</h1>

  <div class="container1">
    <form action="/vehicles" accept-charset="UTF-8" method="get" class="form-container">
      <div class="form-group">
        <input name="utf8" type="hidden" value="✓">
      </div class="form-group">
      <div>
      <input type="text" name="city" id="city" class="form-control" placeholder="Enter City">
      </div>
      <div class="form-group">
        <input type="number" name="price_day" id="price_day" class="form-control" placeholder="Enter Maximum Price">
      </div>
      <div class="form-group">
        <input type="hidden" name="category" id="category" class="form-control" value=<%= params[:category] %>>
      </div>
      <div class="container1">
        <button type="submit" class="btn btn-primary">Search</button>
      </div>
    </form>
  </div>
  <br>

  <div class="container1">
    <div class="cards vehicle-cards">
      <% @vehicles.each do |vehicle| %>
      <%= render './shared/card', vehicle: vehicle %>
      <% end %>
    </div>
  </div>
</div>

app/views/vehicles/new.html.erb
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1500759285222-a95626b934cb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
<div class="container">
      <div class="row">
      <div class="col-sm-6 col-sm-offset-3 col-lg-8 col-lg-offset-2">

  <div id="add-vehicle-form">
    <h1>Post my Vehicool</h1>
    <%= simple_form_for(@vehicle) do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :category, collection: ["car" ,"bicycle" ,"scooter" ,"van"] %>
        <%= f.input :city %>
        <%= f.input :price_day %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: "btn btn-success" %>
    <% end %>
  </div>
  </div>
  </div>
</div>
</div>

app/views/vehicles/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1496224303445-89779ef1ed23?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1489&q=80);">
  <div class="container-fluid bg-show-vehicle">
    <div class="col-md-4 col-sm-12">
        <%= cl_image_tag @vehicle.photo.url, width: "100%", height: "auto"%>
    </div>
    <div class="col-md-4 col-sm-12">
      <div class="booking-details">
        <div class="avatar-circle-show"><%= cl_image_tag @vehicle.user.photo.url(:bright_face)%></div>
        <h1><%= @vehicle.title  %></h1> <br>
        <p><%= @vehicle.description.capitalize %></p>
        <p><%= @vehicle.price_day %> $/day</p>
      </div>
    </div>
    <div class="col-md-4 col-sm-12">
      <div class="form-wrapper" style="margin: 0 auto;">
        <%= simple_form_for ([@vehicle, @booking]) do |f| %>
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.button :submit, "Book Vehicool", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>